#sudo docker-compose -f docker-compose-work.yml up --build
#sudo docker-compose -f docker-compose-work.yml down -v

version: '3'
services:
  banking-migrate:
    build: ../databases/postgres
    command: ["npm", "run", "start"]
    environment:
      - APP_NAME=banking
      - POSTGRES_HOST=dbtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=db-test
    restart: on-failure

  banking:
    build: ./banking
    command: ["npm", "run", "start"]
    environment:
      - POSTGRES_HOST=dbtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=db-test
    ports:
      - "26974:6975"
    restart: on-failure

  dbtest:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-test
    volumes:
      - /opt/projects/697/db/postgres/_data:/var/lib/postgresql/data/
    ports:
      - "26972:5432"
    restart: always
volumes:
  postgres_data:
